version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - app
    groups:
      all-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - pipelines
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
    labels:
      - docker
    groups:
      python-images:
        patterns:
          - "python*"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - terraform
    commit-message:
      prefix: "chore"
      include: "scope"
