local:
  enabled: false

app:
  image:
    tag: 864981720117.dkr.ecr.us-east-1.amazonaws.com/movie-rating
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 256Mi
  ingress:
    enabled: true
    className: alb
    host: {}

migrations:
  image:
    tag: 864981720117.dkr.ecr.us-east-1.amazonaws.com/movie-rating
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 2Gi

secretStore:
  region: us-east-1
