local:
  enabled: false

app:
  image:
    tag: null
    version: null
  resources:
    requests:
      cpu: 15m
      memory: 225M
      ephemeral-storage: 128Mi
    limits:
      cpu: 29m
      memory: 598M
      ephemeral-storage: 256Mi
  ingress:
    enabled: true
    className: alb

migrations:
  image:
    tag: null
    version: null
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 2Gi

secretStore:
  name: null
  region: null
