local:
  enabled: true

otlp:
  endpoint: http://otel-collector.observability.svc.cluster.local:4317

postgresql:
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: movie-rating
    password: movie-rating-password
    database: movie-rating
  primary:
    networkPolicy:
      enabled: false

app:
  image:
    tag: movie-rating
    version: "1.0.0"
  resources:
    requests:
      cpu: 15m # Goldilocks recommendation for 1 replica: 15m
      memory: 225M # Goldilocks recommendation for 1 replica: 15m
      ephemeral-storage: 128Mi
    limits:
      cpu: 29m # Goldilocks recommendation for 1 replica: 15m
      memory: 598M # Goldilocks recommendation for 1 replica: 15m
      ephemeral-storage: 256Mi
  ingress:
    enabled: true
    className: kong
    host: movie-rating.local.com

migrations:
  image:
    tag: movie-rating-migrations
    version: "1.0.0"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 2Gi
    limits:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 2Gi

secretStore:
  name: aws-ssm
  region: us-east-1
