apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/JvictorMarques/movie_rating
      targetRevision: HEAD
      path: k8s/env/local/argo
      directory:
        include: "apps.yaml"
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
