apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-rating
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JvictorMarques/movie_rating
    targetRevision: HEAD
    path: k8s/helm/charts/movie-rating
    helm:
      releaseName: movie-rating
      values: |
        app:
          image:
            tag: movie-rating
            version: movie-rating
        migrations:
          image:
            tag: movie-rating
            version: movie-rating
  destination:
    namespace: movie-rating
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
