apiVersion: v2
name: movie-rating
description: A Helm chart to install the movie-rating application on Kubernetes.

type: application

version: 1.0.1

appVersion: "1.0.1" # x-release-please-version

dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: local.enabled
