{{- if not .Values.local.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "movie-rating.secret-store.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.secretStore.region }}
{{- end }}
