name: Upload App Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/docs/**'
      - 'mkdocs.yml'

jobs:
  upload-docs:
    environment:
      name: docs
      url: https://jvictormarques.github.io/movie-rating/
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: app
    steps:
        - name: Checkout code
          uses: actions/checkout@v6.0.3

        - name: Set up uv
          uses: astral-sh/setup-uv@v8.1.0
          with:
            enable-cache: true
            python-version: ${{ vars.PYTHON_VERSION }}

        - name: Install dependencies
          run: uv sync --frozen

        - name: Configure Git credentials
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

        - name: Upload the docs
          run: uv run mkdocs gh-deploy --force
