name: Terraform Continuous Integration
on:
  workflow_call:
    secrets:
      AWS_ROLE_TO_ASSUME:
        description: 'AWS Role to assume for Terraform operations'
        required: true

jobs:
  ci:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VERSION: 1.15.5
      TF_LINT_VERSION: v0.62.1
    steps:
      - uses: actions/checkout@v6.0.3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.2.2
        with:
          tflint_version: ${{ env.TF_LINT_VERSION }}

      - name: Run TFLint
        run: tflint --recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Run Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
      - name: Comment PR
        uses: actions/github-script@v9.0.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `#### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

              <details><summary>Show Plan</summary>

              \`\`\`terraform
              ${{ steps.plan.outputs.stdout }}
              \`\`\`

              </details>`
            });
