name: Build and Push Helm Charts
on:
  push:
    branches:
      - main
    paths:
      - 'k8s/helm/charts/**'

jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-push-helm-charts.yaml
    with:
      registry: '["ghcr", "ecr"]'
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
