name: Create Infrastructure
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: apply or update'
        type: choice
        required: true
        options:
          - apply
          - update

concurrency:
  group: infrastructure-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: terraform/
    env:
      TF_VAR_ecr_repository_name: '["${{ vars.ECR_DOCKER_REGISTRY }}", "${{ vars.ECR_HELM_REGISTRY }}"]'
      TF_VAR_eks_cluster_name: ${{ vars.EKS_CLUSTER_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4.0.1
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="use_lockfile=true" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        run: terraform apply -auto-approve

  docker:
    name: Build and push Docker images
    if: ${{ inputs.action == 'apply' }}
    needs: terraform
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/_build-push-docker-images.yaml
    with:
      registry: '["ghcr", "ecr"]'
      ecr_repository_name: ${{ vars.ECR_DOCKER_REGISTRY }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

  helm:
    name: Build and push Helm chart
    if: ${{ inputs.action == 'apply' }}
    needs: terraform
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/_build-push-helm-charts.yaml
    with:
      registry: '["ghcr", "ecr"]'
      ecr_repository_name: ${{ vars.ECR_HELM_REGISTRY }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

  app:
    if: ${{ inputs.action == 'apply' }}
    name: Deploy app-of-apps to Kubernetes
    needs: [terraform, docker, helm]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: k8s/env/aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.2.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
          --name ${{ vars.EKS_CLUSTER_NAME }} \
          --region ${{ vars.AWS_REGION }}

      - name: Deploy app-of-apps
        run: |
          kubectl apply -f main.yaml
