name: Test Build Docker Images
on:
  workflow_dispatch:

jobs:
  test-build:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-docker-images.yaml
    with:
      registry: '["ghcr", "ecr"]'
